version: '3.8'

services:
  frontend:
    build:
      context: ..
      args:
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-https://api.interview-ai.ru}
    image: ${DOCKER_REGISTRY}/${DOCKER_REGISTRY_OWNER}/${DOCKER_APP_NAME}:${IMAGE_TAG:-latest}
    ports:
      - '3000:3000'
    restart: always

