/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/{url}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        /** Handle Options */
        options: operations["handle_options__url__options"];
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ping Pong */
        get: operations["ping_pong_ping_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_user_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh Token Route */
        post: operations["refresh_token_route_user_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login For Access Token */
        post: operations["login_for_access_token_user_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/self": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Self */
        get: operations["get_self_user_self_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update User */
        put: operations["update_user_user_put"];
        post?: never;
        /** Delete User */
        delete: operations["delete_user_user_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/all": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get All Users */
        get: operations["get_all_users_user_all_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User By Email */
        get: operations["get_user_by_email_user_email_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Interviews */
        get: operations["list_interviews_interviews_get"];
        put?: never;
        /** Create Interview */
        post: operations["create_interview_interviews_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{session_id}/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Interview Message */
        post: operations["post_interview_message_interviews__session_id__messages_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{session_id}/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Complete Interview */
        post: operations["complete_interview_interviews__session_id__complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/progress/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Interview Progress Summary */
        get: operations["interview_progress_summary_interviews_progress_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/interviews/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Interview */
        get: operations["get_interview_interviews__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_login_for_access_token_user_token_post */
        Body_login_for_access_token_user_token_post: {
            /** Username */
            username: string;
            /** Password */
            password: string;
        };
        /** Body_refresh_token_route_user_refresh_post */
        Body_refresh_token_route_user_refresh_post: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** InterviewCreate */
        InterviewCreate: {
            track: components["schemas"]["InterviewTrackEnum"];
            level: components["schemas"]["InterviewLevelEnum"];
            /** @default technical */
            mode: components["schemas"]["InterviewModeEnum"];
            /**
             * Stress
             * @default false
             */
            stress: boolean;
            /**
             * Max Turns
             * @default 8
             */
            max_turns: number;
        };
        /** InterviewCreateResponse */
        InterviewCreateResponse: {
            session: components["schemas"]["InterviewSessionOut"];
            assistant_message: components["schemas"]["InterviewMessageOut"];
        };
        /** InterviewDetailResponse */
        InterviewDetailResponse: {
            session: components["schemas"]["InterviewSessionOut"];
            /** Messages */
            messages: components["schemas"]["InterviewMessageOut"][];
        };
        /**
         * InterviewLevelEnum
         * @enum {string}
         */
        InterviewLevelEnum: "Junior" | "Middle" | "Senior";
        /** InterviewListItem */
        InterviewListItem: {
            session: components["schemas"]["InterviewSessionOut"];
            /** Overall Score */
            overall_score?: number | null;
        };
        /** InterviewListResponse */
        InterviewListResponse: {
            /** Items */
            items: components["schemas"]["InterviewListItem"][];
            /** Total */
            total: number;
        };
        /** InterviewMessageCreate */
        InterviewMessageCreate: {
            /** Content */
            content: string;
        };
        /** InterviewMessageOut */
        InterviewMessageOut: {
            /** Id */
            id: number;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Created At */
            created_at: string;
        };
        /** InterviewMessage_OVN */
        InterviewMessage_OVN: {
            /** Id */
            id?: number | null;
            /** Role */
            role: string;
            /** Content */
            content: string;
            /** Raw Llm Payload */
            raw_llm_payload?: unknown | null;
            /** Created At */
            created_at: string | null;
        };
        /**
         * InterviewModeEnum
         * @enum {string}
         */
        InterviewModeEnum: "technical" | "hr" | "mixed";
        /** InterviewReplyResponse */
        InterviewReplyResponse: {
            session: components["schemas"]["InterviewSessionOut"];
            assistant_message: components["schemas"]["InterviewMessageOut"];
            /** Interview Finished */
            interview_finished: boolean;
        };
        /** InterviewReportOut */
        InterviewReportOut: {
            /** Id */
            id: number;
            /** Session Id */
            session_id: number;
            /** Summary Text */
            summary_text: string;
            /** Scores */
            scores: {
                [key: string]: unknown;
            };
            /** Recommendations */
            recommendations: unknown[];
            /** Weak Areas */
            weak_areas: unknown[];
            /** Study Plan */
            study_plan: unknown[];
            /** Created At */
            created_at: string;
        };
        /** InterviewReport_VEI */
        InterviewReport_VEI: {
            /** Id */
            id?: number | null;
            /** Summary Text */
            summary_text: string;
            /** Scores */
            scores: unknown;
            /** Recommendations */
            recommendations: unknown;
            /** Weak Areas */
            weak_areas: unknown;
            /** Study Plan */
            study_plan: unknown;
            /** Created At */
            created_at: string | null;
        };
        /** InterviewSessionOut */
        InterviewSessionOut: {
            /** Id */
            id: number;
            /** Track */
            track: string;
            /** Level */
            level: string;
            /** Mode */
            mode: string;
            /** Stress */
            stress: boolean;
            /** Status */
            status: string;
            /** Max Turns */
            max_turns: number;
            /** Created At */
            created_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /** InterviewSession_JFQ */
        InterviewSession_JFQ: {
            /** Id */
            id?: number | null;
            /** Track */
            track: string;
            /** Level */
            level: string;
            /** Mode */
            mode: string;
            /**
             * Stress
             * @default false
             */
            stress: boolean | null;
            /**
             * Status
             * @default active
             */
            status: string | null;
            /**
             * Max Turns
             * @default 8
             */
            max_turns: number | null;
            /** Extra Metadata */
            extra_metadata?: unknown | null;
            /** Created At */
            created_at: string | null;
            /** Completed At */
            completed_at?: string | null;
            /** Interviewmessages */
            interviewmessages?: components["schemas"]["InterviewMessage_OVN"][] | null;
            /** Interviewreports */
            interviewreports?: components["schemas"]["InterviewReport_VEI"][] | null;
        };
        /**
         * InterviewTrackEnum
         * @enum {string}
         */
        InterviewTrackEnum: "Backend" | "Frontend" | "QA" | "DevOps";
        /** ProgressSummaryResponse */
        ProgressSummaryResponse: {
            /** Sessions Completed */
            sessions_completed: number;
            /** Average Overall Score */
            average_overall_score: number | null;
            /** Common Weak Areas */
            common_weak_areas: string[];
        };
        /** RefreshAccessToken */
        RefreshAccessToken: {
            /** Refresh Token */
            refresh_token: string;
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /** Name */
            name: string;
            /** Patronymic */
            patronymic: string;
            /** Surname */
            surname: string;
            /** Date Of Birth */
            date_of_birth: string;
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** UserResponse */
        UserResponse: {
            /** Id */
            id?: number | null;
            /** Name */
            name: string;
            /** Patronymic */
            patronymic: string;
            /** Surname */
            surname: string;
            /** Email */
            email: string;
            /** Date Of Birth */
            date_of_birth: string;
            /**
             * Role
             * @default USER
             */
            role: string | null;
            /** Interviewsessions */
            interviewsessions?: components["schemas"]["InterviewSession_JFQ"][] | null;
        };
        /** UserUpdate */
        UserUpdate: {
            /** Email */
            email?: string | null;
            /** Name */
            name?: string | null;
            /** Patronymic */
            patronymic?: string | null;
            /** Surname */
            surname?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    handle_options__url__options: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                url: unknown;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ping_pong_ping_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    register_user_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_route_user_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_refresh_token_route_user_refresh_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_for_access_token_user_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_for_access_token_user_token_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefreshAccessToken"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_self_user_self_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    update_user_user_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_user_user_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    get_all_users_user_all_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"][];
                };
            };
        };
    };
    get_user_by_email_user_email_get: {
        parameters: {
            query: {
                email: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_interviews_interviews_get: {
        parameters: {
            query?: {
                offset?: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_interview_interviews_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_interview_message_interviews__session_id__messages_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InterviewMessageCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewReplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    complete_interview_interviews__session_id__complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewReportOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    interview_progress_summary_interviews_progress_summary_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummaryResponse"];
                };
            };
        };
    };
    get_interview_interviews__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InterviewDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
