version: '3.8'

services:
  api:
    image: ${DOCKER_REGISTRY}/${DOCKER_REGISTRY_OWNER}/${DOCKER_APP_NAME}:${IMAGE_TAG}

    deploy:
      labels:
        # prometheus
        - "prometheus.enable=true"
        - "prometheus.scrape-port=80"
        - "prometheus.scrape-path=/metrics"
        - "prometheus.job=backend"
        # loki
        - "logging=promtail"
        - "logging_jobname=containerlogs"

        # traefik
        - "traefik.enable=true"
        - "traefik.http.routers.backend.rule=Host(`api.interview-ai.ru`)"
        - "traefik.http.routers.backend.entrypoints=websecure"
        - "traefik.http.routers.backend.tls=true"
        - "traefik.http.routers.backend.tls.certresolver=letsencrypt"
        - "traefik.http.routers.backend.service=backend"
        - "traefik.http.services.backend.loadbalancer.server.port=80"
        - "traefik.swarm.network=traefik-public"

      replicas: 2
      update_config:
        parallelism: 3
        order: start-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 20s
        max_attempts: 5
        window: 120s

    networks:
      - "default"
      - "traefik"

  api_database:
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        order: stop-first
        failure_action: rollback
        delay: 10s
      rollback_config:
        parallelism: 0
        order: stop-first
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3
        window: 120s
      placement:
        constraints: [node.role == manager]

      labels:
        - "logging=promtail"
        - "logging_jobname=containerlogs"

    networks:
      - "default"

networks:
  default:
    name: backend
    external: true
  traefik:
    name: traefik-public
    external: true
